serenity.project.name=Serenity QA Innovation Lab Mobile
serenity.take.screenshots=AFTER_EACH_STEP
webdriver.driver=appium
appium.hub=http://localhost:4723/

#Android capabilities
appium.platformName=Android
appium.platformVersion=11
appium.automationName=uiautomator2
appium.deviceName=13d3c43b
appium.udid=13d3c43b
appium.app=C:/Users/gonza/QA_Lab/QAExamenMobil/src/test/resources/app/mda-2.0.2-23.apk
appium.appPackage=com.saucelabs.mydemoapp.android
appium.appActivity=.view.activities.SplashActivity
